// <auto-generated />
using System;
using AlienApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace alien_api.Migrations
{
    [DbContext(typeof(AlienApiContext))]
    [Migration("20211213192409_nullablebool")]
    partial class nullablebool
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AlienApi.Models.Alien", b =>
                {
                    b.Property<int>("AlienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("BreathesOxygen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("KardashevRating")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("NumberOfPlanets")
                        .HasColumnType("int");

                    b.Property<string>("OriginPlanet")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OriginSystem")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AlienId");

                    b.ToTable("Aliens");

                    b.HasData(
                        new
                        {
                            AlienId = 1,
                            BreathesOxygen = true,
                            Description = "A warlike lizardlike species",
                            KardashevRating = "1",
                            Name = "Turians",
                            NumberOfPlanets = 123,
                            OriginPlanet = "Palaven",
                            OriginSystem = "Palaven"
                        },
                        new
                        {
                            AlienId = 2,
                            BreathesOxygen = false,
                            Description = "A species of short, grey skinned aliens that enjoys experimenting on other lifeforms",
                            KardashevRating = "2",
                            Name = "Greys",
                            NumberOfPlanets = 10,
                            OriginPlanet = "Glarikiblak",
                            OriginSystem = "Falzor"
                        },
                        new
                        {
                            AlienId = 3,
                            BreathesOxygen = true,
                            Description = "An Warlike race of alien clones on a galactic Conquest",
                            KardashevRating = "3",
                            Name = "Irken",
                            NumberOfPlanets = 200,
                            OriginPlanet = "Irken",
                            OriginSystem = "Kelbo"
                        },
                        new
                        {
                            AlienId = 4,
                            BreathesOxygen = false,
                            Description = "A race of sentient Machines created by the Greys",
                            KardashevRating = "2",
                            Name = "Tivbots",
                            NumberOfPlanets = 14,
                            OriginPlanet = "Glarikiblak",
                            OriginSystem = "Falzor"
                        },
                        new
                        {
                            AlienId = 5,
                            BreathesOxygen = true,
                            Description = "A warlike species of of hairless monkeys",
                            KardashevRating = "0",
                            Name = "Humans",
                            NumberOfPlanets = 1,
                            OriginPlanet = "Earth",
                            OriginSystem = "Sol"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
